# AI Optimizer - Composite Action for automatic optimization
name: "AI Pipeline Optimizer"
description: "Optimizes CI/CD pipelines using AI analysis"

inputs:
  github_token:
    description: "GitHub token"
    required: true
  openai_api_key:
    description: "OpenAI API key for advanced analysis"
    required: false
  workflow_run_id:
    description: "Workflow run ID to analyze"
    required: false
  auto_create_pr:
    description: "Automatically create PR with optimizations"
    default: "false"
  confidence_threshold:
    description: "Confidence threshold for applying changes (0-1)"
    default: "0.8"

outputs:
  optimizations_count:
    description: "Number of suggested optimizations"
    value: ${{ steps.optimize.outputs.count }}
  estimated_savings:
    description: "Estimated savings in minutes"
    value: ${{ steps.optimize.outputs.savings }}
  report_url:
    description: "Generated report URL"
    value: ${{ steps.report.outputs.url }}

runs:
  using: "composite"
  steps:
    - name: Collect Run Data
      id: collect
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        RUN_ID: ${{ inputs.workflow_run_id }}
      run: |
        echo "Collecting data for run: ${RUN_ID:-current}"
        
        # Get run data if specified
        if [ -n "$RUN_ID" ]; then
          gh api repos/${{ github.repository }}/actions/runs/$RUN_ID > run_data.json 2>/dev/null || echo '{}' > run_data.json
        else
          echo '{"status": "no_run_specified"}' > run_data.json
        fi

    - name: Analyze and Optimize
      id: optimize
      shell: bash
      run: |
        python << 'PYEOF'
        import json
        import os
        import yaml
        from pathlib import Path

        class PipelineOptimizer:
            def __init__(self):
                self.optimizations = []
                self.total_savings_minutes = 0
            
            def analyze_workflow(self, workflow_path: str) -> list:
                """Analyze a workflow file and generate optimizations."""
                with open(workflow_path) as f:
                    content = f.read()
                    try:
                        config = yaml.safe_load(content)
                    except:
                        return []
                
                optimizations = []
                
                # Optimization 1: Dependency caching
                if "cache" not in content.lower():
                    optimizations.append({
                        "type": "add_cache",
                        "title": "Add dependency caching",
                        "description": "Detected pip/npm usage without cache",
                        "savings_minutes": 2,
                        "confidence": 0.95,
                        "patch": self._generate_cache_patch(config)
                    })
                    self.total_savings_minutes += 2
                
                # Optimization 2: Concurrency control
                if "concurrency" not in content.lower():
                    optimizations.append({
                        "type": "add_concurrency",
                        "title": "Add concurrency control",
                        "description": "Cancel previous runs on same PR",
                        "savings_minutes": 5,
                        "confidence": 0.90,
                        "patch": "concurrency:\n  group: ${{ github.workflow }}-${{ github.ref }}\n  cancel-in-progress: true"
                    })
                    self.total_savings_minutes += 5
                
                # Optimization 3: Parallelization
                jobs = config.get("jobs", {})
                independent_jobs = self._find_independent_jobs(jobs)
                if len(independent_jobs) > 2:
                    optimizations.append({
                        "type": "parallelize",
                        "title": "Parallelize independent jobs",
                        "description": f"Jobs {independent_jobs} can run in parallel",
                        "savings_minutes": 3,
                        "confidence": 0.85,
                        "patch": None
                    })
                    self.total_savings_minutes += 3
                
                # Optimization 4: Sparse checkout
                if "actions/checkout" in content and "sparse-checkout" not in content:
                    optimizations.append({
                        "type": "sparse_checkout",
                        "title": "Use sparse checkout",
                        "description": "Checkout only necessary directories",
                        "savings_minutes": 0.5,
                        "confidence": 0.70,
                        "patch": None
                    })
                    self.total_savings_minutes += 0.5
                
                self.optimizations.extend(optimizations)
                return optimizations
            
            def _generate_cache_patch(self, config: dict) -> str:
                """Generate cache addition patch."""
                return """- name: Cache Dependencies
          uses: actions/cache@v4
          with:
            path: |
              ~/.cache/pip
              node_modules
            key: ${{ runner.os }}-deps-${{ hashFiles('**/requirements.txt', '**/package-lock.json') }}"""
            
            def _find_independent_jobs(self, jobs: dict) -> list:
                """Find jobs without dependencies on each other."""
                independent = []
                for name, config in jobs.items():
                    if "needs" not in config:
                        independent.append(name)
                return independent

        # Run optimizer
        optimizer = PipelineOptimizer()

        # Find workflows
        workflows = list(Path(".github/workflows").glob("*.yml")) + list(Path(".github/workflows").glob("*.yaml"))
        
        for wf in workflows:
            optimizer.analyze_workflow(str(wf))

        # Generate report
        result = {
            "optimizations": optimizer.optimizations,
            "count": len(optimizer.optimizations),
            "total_savings_minutes": optimizer.total_savings_minutes,
            "confidence_avg": sum(o["confidence"] for o in optimizer.optimizations) / len(optimizer.optimizations) if optimizer.optimizations else 0
        }

        # Save result
        with open("optimization_result.json", "w") as f:
            json.dump(result, f, indent=2)

        # GitHub Actions output
        with open(os.environ["GITHUB_OUTPUT"], "a") as f:
            f.write(f"count={result['count']}\n")
            f.write(f"savings={result['total_savings_minutes']}\n")

        print(f"Generated {result['count']} optimizations")
        print(f"Estimated savings: {result['total_savings_minutes']} minutes")
        PYEOF

    - name: Generate Report
      id: report
      shell: bash
      run: |
        cat << 'EOF' >> $GITHUB_STEP_SUMMARY
        ## 🤖 AI Optimization Results
        
        | Metric | Value |
        |--------|-------|
        | Optimizations Found | ${{ steps.optimize.outputs.count }} |
        | Estimated Savings | ${{ steps.optimize.outputs.savings }} min |
        
        ### Recommendations
        EOF
        
        python << 'PYEOF'
        import json
        import os
        
        with open("optimization_result.json") as f:
            result = json.load(f)
        
        with open(os.environ["GITHUB_STEP_SUMMARY"], "a") as summary:
            for opt in result["optimizations"]:
                confidence_bar = "█" * int(opt["confidence"] * 10) + "░" * (10 - int(opt["confidence"] * 10))
                summary.write(f"\n#### {opt['title']}\n")
                summary.write(f"- **Type**: `{opt['type']}`\n")
                summary.write(f"- **Savings**: ~{opt['savings_minutes']} min\n")
                summary.write(f"- **Confidence**: {confidence_bar} {opt['confidence']*100:.0f}%\n")
                summary.write(f"- {opt['description']}\n")
        PYEOF
        
        echo "url=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> $GITHUB_OUTPUT

    - name: Upload Results
      uses: actions/upload-artifact@v4
      with:
        name: optimization-results
        path: optimization_result.json
        retention-days: 30
